[package]
name = "arrow-zarr"
version.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
keywords = ["arrow"]
rust-version = "1.94"

[features]
default = []
icechunk = ["dep:zarrs_icechunk"]
datafusion = ["dep:datafusion"]
s3 = ["zarrs_object_store/aws"]
gcs = ["zarrs_object_store/gcp"]

[dependencies]
arrow = { workspace = true }
arrow-array = { workspace = true }
arrow-schema = { workspace = true }
async-stream = "0.3"
async-trait = { version = "0.1.89" }
bytes = { version = "1.12.1" }
chrono = { version = "0.4.42" }
datafusion = { workspace = true, optional = true }
futures = { version = "0.3.31" }
futures-util = { version = "0.3.31" }
geo-index = "0.3"
geo-traits = {version = "0.3.0" }
geo-types = { version = "0.7.18" }
itertools = { version = "0.14.0" }
ndarray = { version = "0.17.1" }
object_store = { version = "0.13.2" }
tokio = { workspace = true }
tokio-test = { version = "0.4.4" }
wkb = { version = "0.9.2" }
zarrs = { version = "0.23.13", features = ["async"] }
zarrs_filesystem = { version = "0.3.0" }
zarrs_icechunk = { version = "0.5.1", optional = true }
zarrs_metadata = { version = "0.7.5" }
zarrs_object_store = { version = "0.6.2" }
zarrs_storage = { version = "0.4.0", features = ["async"] }

[dev-dependencies]
parquet = { version = "55", features = ["arrow"] }
geos = { version = "8" }
wkt = "0.10"
criterion = { version = "0.7.0", features = ["async_tokio"] }
walkdir = { version = "2.5.0" }

[[bench]]
name = "s3_bench"
harness = false
required-features = ["icechunk", "s3"]

[[bench]]
name = "gcs_bench"
harness = false
required-features = ["icechunk", "gcs"]
