name: Rust

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-fmt:
    name: Check cargo fmt
    runs-on: ubuntu-latest
    container:
      image: amd64/rust
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Run check
        run: |
          cargo fmt --all -- --check

  check-clippy:
    name: Check cargo clippy
    runs-on: ubuntu-latest
    container:
      image: amd64/rust
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Run check
        run: |
          cargo clippy --all-targets --all-features -- -D warnings
